/**
 * `export_database` tool: an Excel file of database rows that never pass through the model. The
 * model writes the query; the server checks it (same rules as `query_database`: SELECT only, enabled
 * tables, per-user filter) and answers with a summary only — how many rows, the columns, a few
 * sample rows. The file itself is generated by the server when the operator clicks the card
 * (`ActivityRow.jsx` → `database/exportFile`), up to `maxRows` rows.
 *
 * `query_database` + `export_excel` stays for small tables the model needs to read anyway; this is
 * for "give me the file": thousands of rows would cost a fortune in tokens, or not fit at all.
 */
import { callFunction } from '@/shared/firebase/functions';

export const EXPORT_DATABASE_TOOL_NAME = 'export_database';

export const EXPORT_DATABASE_TOOL = {
  functionDeclarations: [
    {
      name: EXPORT_DATABASE_TOOL_NAME,
      description:
        "Prepara un file Excel con le righe del database, quando l'operatore chiede di scaricare, " +
        'esportare o avere un file/elenco completo di dati del database. Scrivi solo la query (una ' +
        'SELECT, come per query_database, senza LIMIT se vuole tutto): le righe NON ti vengono ' +
        "restituite, ricevi solo quante sono, le colonne e qualche riga d'esempio; il file lo genera " +
        "il server quando l'operatore clicca il pulsante, fino a un massimo di righe. Preferiscilo a " +
        'query_database + export_excel per qualsiasi esportazione di dati del database. Dopo averlo ' +
        "chiamato, di' quante righe contiene il file e cosa contiene, senza ripetere i dati.",
      parameters: {
        type: 'object',
        properties: {
          connectionId: {
            type: 'string',
            description: "L'id della connessione da interrogare, preso dallo schema ricevuto."
          },
          sql: {
            type: 'string',
            description: 'La query, una singola istruzione SELECT (o WITH ... SELECT).'
          },
          title: {
            type: 'string',
            description: 'Etichetta breve per il file, es. "Pratiche erogate 2026".'
          }
        },
        required: ['connectionId', 'sql', 'title']
      }
    }
  ]
};

/** One call to `export_database`. Returns the `{response}` half of a functionResponse. */
export async function runExportDatabaseCall(call, { schema, round, index, onActivityStart, onActivityEnd }) {
  const { connectionId, sql, title } = call.args || {};
  const connectionLabel = schema.find(entry => entry.connectionId === connectionId)?.label;
  const activityId = `export-db-${round}-${index}`;
  onActivityStart(activityId, { kind: 'export', label: 'Preparo il file' });

  if (!connectionId || !sql) {
    onActivityEnd(activityId, { outcome: 'failed', label: 'File non preparato' });
    return { response: { error: 'connectionId and sql are required' } };
  }

  try {
    const preview = await callFunction('database', 'exportPreview', { connectionId, sql });
    if (!preview.rowCount) {
      onActivityEnd(activityId, { outcome: 'failed', label: 'Nessuna riga da esportare' });
      return { response: { rowCount: 0, note: 'La query non restituisce righe: nessun file.' } };
    }
    onActivityEnd(activityId, {
      outcome: 'done',
      label: 'File pronto',
      exportTitle: title || connectionLabel || 'export',
      detail: `${preview.rowCount.toLocaleString('it-IT')} righe`,
      // what the download button sends back to the server at click time; rows are never kept here
      exportQuery: { connectionId, sql, title: title || '' }
    });
    return {
      response: {
        rowCount: preview.rowCount,
        columns: preview.columns,
        sampleRows: preview.sample,
        ...(preview.capped
          ? {
              warning: `La query restituisce ${preview.totalRows} righe: il file ne conterrà solo le prime ${preview.maxRows}. Dillo all'operatore e suggerisci di restringere la richiesta.`
            }
          : {}),
        note: "Il file non è allegato qui: l'operatore lo scarica dal pulsante nella chat."
      }
    };
  } catch (error) {
    onActivityEnd(activityId, { outcome: 'failed', label: 'File non preparato' });
    // the raw reason goes back to the model, so it can fix the query
    return { response: { error: error.message || 'export failed' } };
  }
}
